module.exports.images = {
  apexLogo: require('../assets/images/apex-logo.png'),
  eyeClose: require('../assets/icons/eye-close.png'),
  eyeOpen: require('../assets/icons/eye-open.png'),
  menu: require('../assets/icons/menu.png'),
  radioButton: require('../assets/icons/radio-button.png'),
  apexBackground: require('../assets/images/apex-background.jpg'),
  search: require('../assets/icons/search.png'),
  book: require('../assets/icons/book.png'),
  message: require('../assets/icons/message.png'),
  close: require('../assets/icons/close.png'),
  leftArrow: require('../assets/icons/left-arrow.png'),
  dashboard: require('../assets/icons/dashboard.png'),
  checklist: require('../assets/icons/checklist.png'),
  backArrow: require('../assets/icons/back-arrow.png'),
  downArrow: require('../assets/icons/down-arrow.png'),
  paperClip: require('../assets/icons/paper-clip.png'),
  edit: require('../assets/icons/edit.png'),
  logout: require('../assets/icons/logout.png'),
  check: require('../assets/images/check.png'),
  calendar: require('../assets/icons/calendar.png'),
  remove: require('../assets/icons/remove.png'),
  video: require('../assets/icons/video.jpg'),
  pdf: require('../assets/icons/pdf.png'),
};
