import {StyleSheet} from 'react-native';
import {RFValue} from 'react-native-responsive-fontsize';
import {colors} from '../../../resources';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  scrollView: {
    flexGrow: 1,
    paddingTop: 30,
    // paddingBottom: 60,
  },
  horizontalScrollView: {
    paddingLeft: 20,
    paddingRight: 10,
  },
  flexRowView: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  topView: {
    marginTop: 10,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginHorizontal: 20,
    backgroundColor: colors.white,
  },
  mainView: {
    marginTop: 20,
    paddingHorizontal: 20,
  },
  headingText: {
    fontWeight: 'bold',
    fontSize: RFValue(15),
    color: colors.black,
  },
  textStyle: {
    flex: 1,
    fontSize: RFValue(10),
    color: colors.black,
  },
  labelStyle: {
    fontWeight: 'normal',
    fontSize: RFValue(11),
    color: colors.black,
  },
  iconStyle: {
    height: 22,
    width: 22,
    marginLeft: 10,
  },
  editIconStyle: {
    height: 13,
    width: 13,
    marginRight: 10,
  },
  btnContainer: {
    marginTop: 10,
    marginBottom: 20,
    marginHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  btnStyle: {
    width: '48%',
  },
  btnTitle: {
    fontSize: RFValue(11),
    color: colors.black,
  },
  tabBtnStyle: {
    height: 38,
    marginRight: 10,
    paddingHorizontal: 14,
    backgroundColor: colors.lightGrey,
  },
  lineSeparator: {
    marginVertical: 15,
    marginHorizontal: 20,
    borderWidth: 0.2,
    borderColor: colors.darkGray,
  },
  verticalLineSeparator: {
    height: '100%',
    borderWidth: 0.2,
    marginHorizontal: 12,
    borderColor: colors.darkGray,
  },
  titleInputContainer: {
    flex: 1,
    borderWidth: 0,
    marginBottom: 0,
    paddingHorizontal: 0,
    backgroundColor: colors.white,
  },
  titleInputStyle: {
    height: 25,
    padding: 0,
    paddingRight: 0,
    fontSize: RFValue(10),
  },
  mediaViewer: {
    marginTop: -5,
    marginBottom: 5,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  imageContainer: {
    marginRight: 15,
    marginBottom: 15,
  },
  imageStyle: {
    height: 90,
    width: 100,
    borderRadius: 5,
    backgroundColor: colors.gray,
  },
  crossIconContainer: {
    top: -5,
    right: -5,
    zIndex: 10,
    position: 'absolute',
  },
  crossIconStyle: {
    width: 20,
    height: 20,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    borderRadius: 15,
  },
  cameraButton: {
    marginTop: 50,
    marginHorizontal: 50,
    width: 150,
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraVideoButton: {
    marginTop: 20,
    marginHorizontal: 50,
    width: 150,
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gallaryButton: {
    marginTop: 20,
    marginHorizontal: 50,
    width: 150,
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pdfButton: {
    marginTop: 20,
    marginHorizontal: 50,
    marginBottom: 40,
    width: 150,
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButton: {
    height: 20,
    width: 20,
    position: 'absolute',
    right: 13,
    top: 13,
  },
});
